[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = ["pip install uv && uv sync --frozen --no-dev"]

[start]
cmd = "uvicorn src.app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
